spring:
  application:
    name: JVM
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gen_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: "123456"
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 100Mb

server:
  port: 8083

mybatis:
  type-aliases-package: com.ray.entity
  mapperLocations: classpath:mapper/*.xml

influxdb:
  url: http://localhost:8083
  token: mvsI8GbRMO-4Di5fKW-1Qkr7zd8OU7Lz5k8h_LL2yfPig9GpQMBTrQvESREXrJWWtYfKUqvD_Rf-jhC90P4LkA==
  org: ray
  bucket: jvm-metrics

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true



logging:
  level:
    com.ldy: DEBUG
